version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    command: postgres -c 'max_connections=1200'
    environment:
      POSTGRES_DB: 'blockscout'
      POSTGRES_PASSWORD: 'blockscout'
      POSTGRES_USER: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - 5432:5432
    volumes:
      - ./blockscout-db-data:/var/lib/postgresql/data/
